import { SendInvoice } from "../definitions/SendInvoice";
import { SendInvoiceResponse } from "../definitions/SendInvoiceResponse";
import { SendInvoiceApi } from "../definitions/SendInvoiceApi";
import { SendInvoiceApiResponse } from "../definitions/SendInvoiceApiResponse";
import { SendInvoiceXml } from "../definitions/SendInvoiceXml";
import { SendInvoiceXmlResponse } from "../definitions/SendInvoiceXmlResponse";
import { SendInvoiceXmlWithoutInvoiceNumber } from "../definitions/SendInvoiceXmlWithoutInvoiceNumber";
import { SendInvoiceXmlWithoutInvoiceNumberResponse } from "../definitions/SendInvoiceXmlWithoutInvoiceNumberResponse";
import { SendCurrencyInvoice } from "../definitions/SendCurrencyInvoice";
import { SendCurrencyInvoiceResponse } from "../definitions/SendCurrencyInvoiceResponse";
import { SendCurrencyInvoiceApi } from "../definitions/SendCurrencyInvoiceApi";
import { SendCurrencyInvoiceApiResponse } from "../definitions/SendCurrencyInvoiceApiResponse";
import { SendArchiveInvoice } from "../definitions/SendArchiveInvoice";
import { SendArchiveInvoiceResponse } from "../definitions/SendArchiveInvoiceResponse";
import { SendArchiveInvoiceApi } from "../definitions/SendArchiveInvoiceApi";
import { SendArchiveInvoiceApiResponse } from "../definitions/SendArchiveInvoiceApiResponse";
import { SendArchiveInvoiceXml } from "../definitions/SendArchiveInvoiceXml";
import { SendArchiveInvoiceXmlResponse } from "../definitions/SendArchiveInvoiceXmlResponse";
import { SendArchiveInvoiceXmlWithoutInvoiceNumber } from "../definitions/SendArchiveInvoiceXmlWithoutInvoiceNumber";
import { SendArchiveInvoiceXmlWithoutInvoiceNumberResponse } from "../definitions/SendArchiveInvoiceXmlWithoutInvoiceNumberResponse";
import { SendInvoiceReply } from "../definitions/SendInvoiceReply";
import { SendInvoiceReplyResponse } from "../definitions/SendInvoiceReplyResponse";
import { UpdateInvoiceState } from "../definitions/UpdateInvoiceState";
import { UpdateInvoiceStateResponse } from "../definitions/UpdateInvoiceStateResponse";
import { DirectInvoice } from "../definitions/DirectInvoice";
import { DirectInvoiceResponse } from "../definitions/DirectInvoiceResponse";
import { SearchInvoice } from "../definitions/SearchInvoice";
import { SearchInvoiceResponse } from "../definitions/SearchInvoiceResponse";
import { SearchAllInvoice } from "../definitions/SearchAllInvoice";
import { SearchAllInvoiceResponse } from "../definitions/SearchAllInvoiceResponse";
import { SearchExternalInvoice } from "../definitions/SearchExternalInvoice";
import { SearchExternalInvoiceResponse } from "../definitions/SearchExternalInvoiceResponse";
import { SearchArchiveInvoice } from "../definitions/SearchArchiveInvoice";
import { SearchArchiveInvoiceResponse } from "../definitions/SearchArchiveInvoiceResponse";
import { ArchiveInvoice } from "../definitions/ArchiveInvoice";
import { ArchiveInvoiceResponse } from "../definitions/ArchiveInvoiceResponse";
import { DeArchiveInvoice } from "../definitions/DeArchiveInvoice";
import { DeArchiveInvoiceResponse } from "../definitions/DeArchiveInvoiceResponse";
import { CancelArchiveInvoice } from "../definitions/CancelArchiveInvoice";
import { CancelArchiveInvoiceResponse } from "../definitions/CancelArchiveInvoiceResponse";
import { SendArchiveInvoiceReport } from "../definitions/SendArchiveInvoiceReport";
import { SendArchiveInvoiceReportResponse } from "../definitions/SendArchiveInvoiceReportResponse";
import { SearchArchiveInvoiceReport } from "../definitions/SearchArchiveInvoiceReport";
import { SearchArchiveInvoiceReportResponse } from "../definitions/SearchArchiveInvoiceReportResponse";
import { SendArchiveInvoiceMail } from "../definitions/SendArchiveInvoiceMail";
import { SendArchiveInvoiceMailResponse } from "../definitions/SendArchiveInvoiceMailResponse";
import { GetEttnList } from "../definitions/GetEttnList";
import { GetEttnListResponse } from "../definitions/GetEttnListResponse";
import { GetAbbreviationReport } from "../definitions/GetAbbreviationReport";
import { GetAbbreviationReportResponse } from "../definitions/GetAbbreviationReportResponse";
import { GetAbbreviationDetailReport } from "../definitions/GetAbbreviationDetailReport";
import { GetAbbreviationDetailReportResponse } from "../definitions/GetAbbreviationDetailReportResponse";
import { CreateReturnReceipt } from "../definitions/CreateReturnReceipt";
import { CreateReturnReceiptResponse } from "../definitions/CreateReturnReceiptResponse";
import { SendDespatchAdvice } from "../definitions/SendDespatchAdvice";
import { SendDespatchAdviceResponse } from "../definitions/SendDespatchAdviceResponse";
import { SendDespatchAdviceXml } from "../definitions/SendDespatchAdviceXml";
import { SendDespatchAdviceXmlResponse } from "../definitions/SendDespatchAdviceXmlResponse";
import { SendDespatchAdviceXmlWithoutDespatchAdviceNumber } from "../definitions/SendDespatchAdviceXmlWithoutDespatchAdviceNumber";
import { SendDespatchAdviceXmlWithoutDespatchAdviceNumberResponse } from "../definitions/SendDespatchAdviceXmlWithoutDespatchAdviceNumberResponse";
import { SearchDespatchAdvice } from "../definitions/SearchDespatchAdvice";
import { SearchDespatchAdviceResponse } from "../definitions/SearchDespatchAdviceResponse";
import { SendReceiptAdvice } from "../definitions/SendReceiptAdvice";
import { SendReceiptAdviceResponse } from "../definitions/SendReceiptAdviceResponse";
import { SendReceiptAdviceXml } from "../definitions/SendReceiptAdviceXml";
import { SendReceiptAdviceXmlResponse } from "../definitions/SendReceiptAdviceXmlResponse";
import { SendReceiptAdviceXmlWithoutReceiptAdviceNumber } from "../definitions/SendReceiptAdviceXmlWithoutReceiptAdviceNumber";
import { SendReceiptAdviceXmlWithoutReceiptAdviceNumberResponse } from "../definitions/SendReceiptAdviceXmlWithoutReceiptAdviceNumberResponse";
import { SearchReceiptAdvice } from "../definitions/SearchReceiptAdvice";
import { SearchReceiptAdviceResponse } from "../definitions/SearchReceiptAdviceResponse";
import { SendEsmm } from "../definitions/SendEsmm";
import { SendEsmmResponse } from "../definitions/SendEsmmResponse";
import { SendEsmmXml } from "../definitions/SendEsmmXml";
import { SendEsmmXmlResponse } from "../definitions/SendEsmmXmlResponse";
import { SearchEsmm } from "../definitions/SearchEsmm";
import { SearchEsmmResponse } from "../definitions/SearchEsmmResponse";
import { CancelEsmm } from "../definitions/CancelEsmm";
import { CancelEsmmResponse } from "../definitions/CancelEsmmResponse";
import { GetCompanyBalance } from "../definitions/GetCompanyBalance";
import { GetCompanyBalanceResponse } from "../definitions/GetCompanyBalanceResponse";

export interface InvoiceServiceBasicHttpEndpoint {
    SendInvoice(sendInvoice: SendInvoice, callback: (err: any, result: SendInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendInvoiceApi(sendInvoiceApi: SendInvoiceApi, callback: (err: any, result: SendInvoiceApiResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendInvoiceXml(sendInvoiceXml: SendInvoiceXml, callback: (err: any, result: SendInvoiceXmlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendInvoiceXmlWithoutInvoiceNumber(sendInvoiceXmlWithoutInvoiceNumber: SendInvoiceXmlWithoutInvoiceNumber, callback: (err: any, result: SendInvoiceXmlWithoutInvoiceNumberResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendCurrencyInvoice(sendCurrencyInvoice: SendCurrencyInvoice, callback: (err: any, result: SendCurrencyInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendCurrencyInvoiceApi(sendCurrencyInvoiceApi: SendCurrencyInvoiceApi, callback: (err: any, result: SendCurrencyInvoiceApiResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendArchiveInvoice(sendArchiveInvoice: SendArchiveInvoice, callback: (err: any, result: SendArchiveInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendArchiveInvoiceApi(sendArchiveInvoiceApi: SendArchiveInvoiceApi, callback: (err: any, result: SendArchiveInvoiceApiResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendArchiveInvoiceXml(sendArchiveInvoiceXml: SendArchiveInvoiceXml, callback: (err: any, result: SendArchiveInvoiceXmlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendArchiveInvoiceXmlWithoutInvoiceNumber(sendArchiveInvoiceXmlWithoutInvoiceNumber: SendArchiveInvoiceXmlWithoutInvoiceNumber, callback: (err: any, result: SendArchiveInvoiceXmlWithoutInvoiceNumberResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendInvoiceReply(sendInvoiceReply: SendInvoiceReply, callback: (err: any, result: SendInvoiceReplyResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateInvoiceState(updateInvoiceState: UpdateInvoiceState, callback: (err: any, result: UpdateInvoiceStateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DirectInvoice(directInvoice: DirectInvoice, callback: (err: any, result: DirectInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SearchInvoice(searchInvoice: SearchInvoice, callback: (err: any, result: SearchInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SearchAllInvoice(searchAllInvoice: SearchAllInvoice, callback: (err: any, result: SearchAllInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SearchExternalInvoice(searchExternalInvoice: SearchExternalInvoice, callback: (err: any, result: SearchExternalInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SearchArchiveInvoice(searchArchiveInvoice: SearchArchiveInvoice, callback: (err: any, result: SearchArchiveInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ArchiveInvoice(archiveInvoice: ArchiveInvoice, callback: (err: any, result: ArchiveInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DeArchiveInvoice(deArchiveInvoice: DeArchiveInvoice, callback: (err: any, result: DeArchiveInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelArchiveInvoice(cancelArchiveInvoice: CancelArchiveInvoice, callback: (err: any, result: CancelArchiveInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendArchiveInvoiceReport(sendArchiveInvoiceReport: SendArchiveInvoiceReport, callback: (err: any, result: SendArchiveInvoiceReportResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SearchArchiveInvoiceReport(searchArchiveInvoiceReport: SearchArchiveInvoiceReport, callback: (err: any, result: SearchArchiveInvoiceReportResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendArchiveInvoiceMail(sendArchiveInvoiceMail: SendArchiveInvoiceMail, callback: (err: any, result: SendArchiveInvoiceMailResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetEttnList(getEttnList: GetEttnList, callback: (err: any, result: GetEttnListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAbbreviationReport(getAbbreviationReport: GetAbbreviationReport, callback: (err: any, result: GetAbbreviationReportResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAbbreviationDetailReport(getAbbreviationDetailReport: GetAbbreviationDetailReport, callback: (err: any, result: GetAbbreviationDetailReportResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateReturnReceipt(createReturnReceipt: CreateReturnReceipt, callback: (err: any, result: CreateReturnReceiptResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendDespatchAdvice(sendDespatchAdvice: SendDespatchAdvice, callback: (err: any, result: SendDespatchAdviceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendDespatchAdviceXml(sendDespatchAdviceXml: SendDespatchAdviceXml, callback: (err: any, result: SendDespatchAdviceXmlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendDespatchAdviceXmlWithoutDespatchAdviceNumber(sendDespatchAdviceXmlWithoutDespatchAdviceNumber: SendDespatchAdviceXmlWithoutDespatchAdviceNumber, callback: (err: any, result: SendDespatchAdviceXmlWithoutDespatchAdviceNumberResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SearchDespatchAdvice(searchDespatchAdvice: SearchDespatchAdvice, callback: (err: any, result: SearchDespatchAdviceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendReceiptAdvice(sendReceiptAdvice: SendReceiptAdvice, callback: (err: any, result: SendReceiptAdviceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendReceiptAdviceXml(sendReceiptAdviceXml: SendReceiptAdviceXml, callback: (err: any, result: SendReceiptAdviceXmlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendReceiptAdviceXmlWithoutReceiptAdviceNumber(sendReceiptAdviceXmlWithoutReceiptAdviceNumber: SendReceiptAdviceXmlWithoutReceiptAdviceNumber, callback: (err: any, result: SendReceiptAdviceXmlWithoutReceiptAdviceNumberResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SearchReceiptAdvice(searchReceiptAdvice: SearchReceiptAdvice, callback: (err: any, result: SearchReceiptAdviceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendESMM(sendEsmm: SendEsmm, callback: (err: any, result: SendEsmmResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendESMMXml(sendEsmmXml: SendEsmmXml, callback: (err: any, result: SendEsmmXmlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SearchESMM(searchEsmm: SearchEsmm, callback: (err: any, result: SearchEsmmResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelESMM(cancelEsmm: CancelEsmm, callback: (err: any, result: CancelEsmmResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCompanyBalance(getCompanyBalance: GetCompanyBalance, callback: (err: any, result: GetCompanyBalanceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
