
/**
 * ExcludeDetailStatusList
 * @targetNSAlias `tns`
 * @targetNamespace `http://schemas.datacontract.org/2004/07/EInvoice.Service.Model`
 */
export interface ExcludeDetailStatusList {
    /** InvoiceDetailStatus|xs:string|Zarflanmadi,Zarf_Kuyruga_Eklendi,Zarf_Isleniyor,Zip_Dosyasi_Degil,ZarfId_Uzunlugu_Gecersiz,Zarf_Arsivden_Kopyalanamadi,Zip_Acilamadi,Zip_Bir_Dosya_Icermeli,XML_Dosyasi_Degil,Zarf_ID_Ve_XML_Dosyasinin_Adi_Ayni_Olmali,Dokuman_Ayristirilamadi,Zarf_ID_Yok,Zarf_ID_VE_Zip_Dosyasi_Adi_Ayni_Olmali,Gecersiz_Versiyon,Schematron_Kontrol_Sonucu_Hatali,Xml_Sema_Kontrolundan_Gecemedi,Imza_Sahibi_TCKN_VKN_Alinamadi,Imza_Kaydedilemedi,Gonderilen_Zarf_Kayitli_bir_Fatura_Icermelidir,Gonderilen_Zarf_Kayitli_bir_Belge_Icermektedir,Yetki_Kontrol_Edilemedi,Gonderici_Birim_Yetkisi_Yok,Posta_Kutusu_Yetkisi_Yok,Islem_Yetkisi_Yok,Imza_Yetkisi_Kontrol_Edilemedi,Imza_Sahibi_Yetkisi,Gecersiz_Imza,Adres_Kontrol_Edilemedi,Adres_Bulunamadi,Kullanici_Eklenemedi,Kullanici_Silinemedi,Sistem_Yaniti_Hazirlanamadi,Sistem_Hatasi,Zarf_Basariyla_Islendi,Dokuman_Bulunan_Adrese_Gonderilemedi,Dokuman_Gonderimi_Basarisiz_Tekrar_Gonderme_Sonlandi,Hedeften_Sistem_Yaniti_Gelmedi,Hedeften_Sistem_Yaniti_Basarisiz_Geldi,Fatura_Iptale_Konu_Edildi,Basariyla_Tamamlandi */
    InvoiceDetailStatus?: Array<string>;
}
