import { GetSystemDate } from "../definitions/GetSystemDate";
import { GetSystemDateResponse } from "../definitions/GetSystemDateResponse";
import { GetSystemDateWithFormat } from "../definitions/GetSystemDateWithFormat";
import { GetSystemDateWithFormatResponse } from "../definitions/GetSystemDateWithFormatResponse";
import { IsEInvoiceUser } from "../definitions/IsEInvoiceUser";
import { IsEInvoiceUserResponse } from "../definitions/IsEInvoiceUserResponse";
import { GetEInvoiceUsers } from "../definitions/GetEInvoiceUsers";
import { GetEInvoiceUsersResponse } from "../definitions/GetEInvoiceUsersResponse";
import { FilterEInvoiceUsers } from "../definitions/FilterEInvoiceUsers";
import { FilterEInvoiceUsersResponse } from "../definitions/FilterEInvoiceUsersResponse";
import { GetUserAliasses } from "../definitions/GetUserAliasses";
import { GetUserAliassesResponse } from "../definitions/GetUserAliassesResponse";
import { SetXsltView } from "../definitions/SetXsltView";
import { SetXsltViewResponse } from "../definitions/SetXsltViewResponse";
import { GetXsltView } from "../definitions/GetXsltView";
import { GetXsltViewResponse } from "../definitions/GetXsltViewResponse";
import { ValidateInvoice } from "../definitions/ValidateInvoice";
import { ValidateInvoiceResponse } from "../definitions/ValidateInvoiceResponse";
import { GetInboxInvoices } from "../definitions/GetInboxInvoices";
import { GetInboxInvoicesResponse } from "../definitions/GetInboxInvoicesResponse";
import { GetInboxInvoiceList } from "../definitions/GetInboxInvoiceList";
import { GetInboxInvoiceListResponse } from "../definitions/GetInboxInvoiceListResponse";
import { GetInboxInvoice } from "../definitions/GetInboxInvoice";
import { GetInboxInvoiceResponse } from "../definitions/GetInboxInvoiceResponse";
import { GetInboxInvoicesData } from "../definitions/GetInboxInvoicesData";
import { GetInboxInvoicesDataResponse } from "../definitions/GetInboxInvoicesDataResponse";
import { GetInboxInvoiceData } from "../definitions/GetInboxInvoiceData";
import { GetInboxInvoiceDataResponse } from "../definitions/GetInboxInvoiceDataResponse";
import { QueryInboxInvoiceStatus } from "../definitions/QueryInboxInvoiceStatus";
import { QueryInboxInvoiceStatusResponse } from "../definitions/QueryInboxInvoiceStatusResponse";
import { SetInvoicesTaken } from "../definitions/SetInvoicesTaken";
import { SetInvoicesTakenResponse } from "../definitions/SetInvoicesTakenResponse";
import { SendDocumentResponse } from "../definitions/SendDocumentResponse";
import { SendDocumentResponseResponse } from "../definitions/SendDocumentResponseResponse";
import { QueryDocumentResponseStatus } from "../definitions/QueryDocumentResponseStatus";
import { QueryDocumentResponseStatusResponse } from "../definitions/QueryDocumentResponseStatusResponse";
import { GetOutboxInvoices } from "../definitions/GetOutboxInvoices";
import { GetOutboxInvoicesResponse } from "../definitions/GetOutboxInvoicesResponse";
import { GetOutboxInvoiceList } from "../definitions/GetOutboxInvoiceList";
import { GetOutboxInvoiceListResponse } from "../definitions/GetOutboxInvoiceListResponse";
import { GetOutboxInvoice } from "../definitions/GetOutboxInvoice";
import { GetOutboxInvoiceResponse } from "../definitions/GetOutboxInvoiceResponse";
import { GetOutboxInvoicesData } from "../definitions/GetOutboxInvoicesData";
import { GetOutboxInvoicesDataResponse } from "../definitions/GetOutboxInvoicesDataResponse";
import { GetOutboxInvoiceData } from "../definitions/GetOutboxInvoiceData";
import { GetOutboxInvoiceDataResponse } from "../definitions/GetOutboxInvoiceDataResponse";
import { QueryOutboxInvoiceStatus } from "../definitions/QueryOutboxInvoiceStatus";
import { QueryOutboxInvoiceStatusResponse } from "../definitions/QueryOutboxInvoiceStatusResponse";
import { QueryInvoiceGtbResponses } from "../definitions/QueryInvoiceGtbResponses";
import { QueryInvoiceGtbResponsesResponse } from "../definitions/QueryInvoiceGtbResponsesResponse";
import { SaveAsDraft } from "../definitions/SaveAsDraft";
import { SaveAsDraftResponse } from "../definitions/SaveAsDraftResponse";
import { SendInvoice } from "../definitions/SendInvoice";
import { SendInvoiceResponse } from "../definitions/SendInvoiceResponse";
import { CompressedSaveAsDraft } from "../definitions/CompressedSaveAsDraft";
import { CompressedSaveAsDraftResponse } from "../definitions/CompressedSaveAsDraftResponse";
import { CompressedSendInvoice } from "../definitions/CompressedSendInvoice";
import { CompressedSendInvoiceResponse } from "../definitions/CompressedSendInvoiceResponse";
import { SendDraft } from "../definitions/SendDraft";
import { SendDraftResponse } from "../definitions/SendDraftResponse";
import { CancelDraft } from "../definitions/CancelDraft";
import { CancelDraftResponse } from "../definitions/CancelDraftResponse";
import { GetInboxInvoiceView } from "../definitions/GetInboxInvoiceView";
import { GetInboxInvoiceViewResponse } from "../definitions/GetInboxInvoiceViewResponse";
import { GetOutboxInvoiceView } from "../definitions/GetOutboxInvoiceView";
import { GetOutboxInvoiceViewResponse } from "../definitions/GetOutboxInvoiceViewResponse";
import { GetOutboxInvoiceResponseView } from "../definitions/GetOutboxInvoiceResponseView";
import { GetOutboxInvoiceResponseViewResponse } from "../definitions/GetOutboxInvoiceResponseViewResponse";
import { GetInboxInvoiceStatusWithLogs } from "../definitions/GetInboxInvoiceStatusWithLogs";
import { GetInboxInvoiceStatusWithLogsResponse } from "../definitions/GetInboxInvoiceStatusWithLogsResponse";
import { GetOutboxInvoiceStatusWithLogs } from "../definitions/GetOutboxInvoiceStatusWithLogs";
import { GetOutboxInvoiceStatusWithLogsResponse } from "../definitions/GetOutboxInvoiceStatusWithLogsResponse";
import { RetrySendInvoices } from "../definitions/RetrySendInvoices";
import { RetrySendInvoicesResponse } from "../definitions/RetrySendInvoicesResponse";
import { CloneInvoices } from "../definitions/CloneInvoices";
import { CloneInvoicesResponse } from "../definitions/CloneInvoicesResponse";
import { CancelEArchiveInvoice } from "../definitions/CancelEArchiveInvoice";
import { CancelEArchiveInvoiceResponse } from "../definitions/CancelEArchiveInvoiceResponse";
import { GetInboxInvoicePdf } from "../definitions/GetInboxInvoicePdf";
import { GetInboxInvoicePdfResponse } from "../definitions/GetInboxInvoicePdfResponse";
import { GetOutboxInvoicePdf } from "../definitions/GetOutboxInvoicePdf";
import { GetOutboxInvoicePdfResponse } from "../definitions/GetOutboxInvoicePdfResponse";
import { ChangeInvoiceArchiveStatus } from "../definitions/ChangeInvoiceArchiveStatus";
import { ChangeInvoiceArchiveStatusResponse } from "../definitions/ChangeInvoiceArchiveStatusResponse";
import { GetSystemUsersCompressedList } from "../definitions/GetSystemUsersCompressedList";
import { GetSystemUsersCompressedListResponse } from "../definitions/GetSystemUsersCompressedListResponse";
import { GetSystemUsersCompressedListOld } from "../definitions/GetSystemUsersCompressedListOld";
import { GetSystemUsersCompressedListOldResponse } from "../definitions/GetSystemUsersCompressedListOldResponse";
import { ImportExistingInvoice } from "../definitions/ImportExistingInvoice";
import { ImportExistingInvoiceResponse } from "../definitions/ImportExistingInvoiceResponse";
import { QueueInvoiceNotification } from "../definitions/QueueInvoiceNotification";
import { QueueInvoiceNotificationResponse } from "../definitions/QueueInvoiceNotificationResponse";
import { GetInvoiceEnvelope } from "../definitions/GetInvoiceEnvelope";
import { GetInvoiceEnvelopeResponse } from "../definitions/GetInvoiceEnvelopeResponse";
import { TestConnection } from "../definitions/TestConnection";
import { TestConnectionResponse } from "../definitions/TestConnectionResponse";
import { GetSummaryReport } from "../definitions/GetSummaryReport";
import { GetSummaryReportResponse } from "../definitions/GetSummaryReportResponse";
import { WhoAmI } from "../definitions/WhoAmI";
import { WhoAmIResponse } from "../definitions/WhoAmIResponse";
import { MoveToDraftStatus } from "../definitions/MoveToDraftStatus";
import { MoveToDraftStatusResponse } from "../definitions/MoveToDraftStatusResponse";
import { TransferInboxInvoiceToAnotherBranch } from "../definitions/TransferInboxInvoiceToAnotherBranch";
import { TransferInboxInvoiceToAnotherBranchResponse } from "../definitions/TransferInboxInvoiceToAnotherBranchResponse";

export interface BasicHttpBindingIIntegration {
    GetSystemDate(getSystemDate: GetSystemDate, callback: (err: any, result: GetSystemDateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSystemDateWithFormat(getSystemDateWithFormat: GetSystemDateWithFormat, callback: (err: any, result: GetSystemDateWithFormatResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    IsEInvoiceUser(isEInvoiceUser: IsEInvoiceUser, callback: (err: any, result: IsEInvoiceUserResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetEInvoiceUsers(getEInvoiceUsers: GetEInvoiceUsers, callback: (err: any, result: GetEInvoiceUsersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    FilterEInvoiceUsers(filterEInvoiceUsers: FilterEInvoiceUsers, callback: (err: any, result: FilterEInvoiceUsersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetUserAliasses(getUserAliasses: GetUserAliasses, callback: (err: any, result: GetUserAliassesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetXsltView(setXsltView: SetXsltView, callback: (err: any, result: SetXsltViewResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetXsltView(getXsltView: GetXsltView, callback: (err: any, result: GetXsltViewResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ValidateInvoice(validateInvoice: ValidateInvoice, callback: (err: any, result: ValidateInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInboxInvoices(getInboxInvoices: GetInboxInvoices, callback: (err: any, result: GetInboxInvoicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInboxInvoiceList(getInboxInvoiceList: GetInboxInvoiceList, callback: (err: any, result: GetInboxInvoiceListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInboxInvoice(getInboxInvoice: GetInboxInvoice, callback: (err: any, result: GetInboxInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInboxInvoicesData(getInboxInvoicesData: GetInboxInvoicesData, callback: (err: any, result: GetInboxInvoicesDataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInboxInvoiceData(getInboxInvoiceData: GetInboxInvoiceData, callback: (err: any, result: GetInboxInvoiceDataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    QueryInboxInvoiceStatus(queryInboxInvoiceStatus: QueryInboxInvoiceStatus, callback: (err: any, result: QueryInboxInvoiceStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetInvoicesTaken(setInvoicesTaken: SetInvoicesTaken, callback: (err: any, result: SetInvoicesTakenResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendDocumentResponse(sendDocumentResponse: SendDocumentResponse, callback: (err: any, result: SendDocumentResponseResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    QueryDocumentResponseStatus(queryDocumentResponseStatus: QueryDocumentResponseStatus, callback: (err: any, result: QueryDocumentResponseStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoices(getOutboxInvoices: GetOutboxInvoices, callback: (err: any, result: GetOutboxInvoicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoiceList(getOutboxInvoiceList: GetOutboxInvoiceList, callback: (err: any, result: GetOutboxInvoiceListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoice(getOutboxInvoice: GetOutboxInvoice, callback: (err: any, result: GetOutboxInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoicesData(getOutboxInvoicesData: GetOutboxInvoicesData, callback: (err: any, result: GetOutboxInvoicesDataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoiceData(getOutboxInvoiceData: GetOutboxInvoiceData, callback: (err: any, result: GetOutboxInvoiceDataResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    QueryOutboxInvoiceStatus(queryOutboxInvoiceStatus: QueryOutboxInvoiceStatus, callback: (err: any, result: QueryOutboxInvoiceStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    QueryInvoiceGtbResponses(queryInvoiceGtbResponses: QueryInvoiceGtbResponses, callback: (err: any, result: QueryInvoiceGtbResponsesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SaveAsDraft(saveAsDraft: SaveAsDraft, callback: (err: any, result: SaveAsDraftResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendInvoice(sendInvoice: SendInvoice, callback: (err: any, result: SendInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CompressedSaveAsDraft(compressedSaveAsDraft: CompressedSaveAsDraft, callback: (err: any, result: CompressedSaveAsDraftResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CompressedSendInvoice(compressedSendInvoice: CompressedSendInvoice, callback: (err: any, result: CompressedSendInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SendDraft(sendDraft: SendDraft, callback: (err: any, result: SendDraftResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelDraft(cancelDraft: CancelDraft, callback: (err: any, result: CancelDraftResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInboxInvoiceView(getInboxInvoiceView: GetInboxInvoiceView, callback: (err: any, result: GetInboxInvoiceViewResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoiceView(getOutboxInvoiceView: GetOutboxInvoiceView, callback: (err: any, result: GetOutboxInvoiceViewResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoiceResponseView(getOutboxInvoiceResponseView: GetOutboxInvoiceResponseView, callback: (err: any, result: GetOutboxInvoiceResponseViewResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInboxInvoiceStatusWithLogs(getInboxInvoiceStatusWithLogs: GetInboxInvoiceStatusWithLogs, callback: (err: any, result: GetInboxInvoiceStatusWithLogsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoiceStatusWithLogs(getOutboxInvoiceStatusWithLogs: GetOutboxInvoiceStatusWithLogs, callback: (err: any, result: GetOutboxInvoiceStatusWithLogsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RetrySendInvoices(retrySendInvoices: RetrySendInvoices, callback: (err: any, result: RetrySendInvoicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CloneInvoices(cloneInvoices: CloneInvoices, callback: (err: any, result: CloneInvoicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelEArchiveInvoice(cancelEArchiveInvoice: CancelEArchiveInvoice, callback: (err: any, result: CancelEArchiveInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInboxInvoicePdf(getInboxInvoicePdf: GetInboxInvoicePdf, callback: (err: any, result: GetInboxInvoicePdfResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOutboxInvoicePdf(getOutboxInvoicePdf: GetOutboxInvoicePdf, callback: (err: any, result: GetOutboxInvoicePdfResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ChangeInvoiceArchiveStatus(changeInvoiceArchiveStatus: ChangeInvoiceArchiveStatus, callback: (err: any, result: ChangeInvoiceArchiveStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSystemUsersCompressedList(getSystemUsersCompressedList: GetSystemUsersCompressedList, callback: (err: any, result: GetSystemUsersCompressedListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSystemUsersCompressedListOld(getSystemUsersCompressedListOld: GetSystemUsersCompressedListOld, callback: (err: any, result: GetSystemUsersCompressedListOldResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ImportExistingInvoice(importExistingInvoice: ImportExistingInvoice, callback: (err: any, result: ImportExistingInvoiceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    QueueInvoiceNotification(queueInvoiceNotification: QueueInvoiceNotification, callback: (err: any, result: QueueInvoiceNotificationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetInvoiceEnvelope(getInvoiceEnvelope: GetInvoiceEnvelope, callback: (err: any, result: GetInvoiceEnvelopeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TestConnection(testConnection: TestConnection, callback: (err: any, result: TestConnectionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSummaryReport(getSummaryReport: GetSummaryReport, callback: (err: any, result: GetSummaryReportResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    WhoAmI(whoAmI: WhoAmI, callback: (err: any, result: WhoAmIResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    MoveToDraftStatus(moveToDraftStatus: MoveToDraftStatus, callback: (err: any, result: MoveToDraftStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    TransferInboxInvoiceToAnotherBranch(transferInboxInvoiceToAnotherBranch: TransferInboxInvoiceToAnotherBranch, callback: (err: any, result: TransferInboxInvoiceToAnotherBranchResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
