-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6/JgQ12Tv67R9/Nq
8ekrdvrTG5PjkVjRzydBkoiKSs6gCgYIKoZIzj0DAQehRANCAAR7DpafI21w9CPg
VYgxwImkzVVeV/XpaOSQrmCi6DdfxFIkvLWnRp6TYgRKnpuM/lgVJ2FM5eYpEMjW
giGrUVC7
-----END PRIVATE KEY-----